### ISSUE TITLE
Installing on Yosemite

### ISSUE THREAD

**Issue by briantjacobs** [developmentseed/landsat-util#27] opened 2015-01-21 23:16 UTC
Trying to get this running on a Yosemite machine. Running into some dependency issues:

```
$: brew install https://raw.githubusercontent.com/developmentseed/landsat-util/master/Formula/landsat-util.rb
######################################################################## 100.0%
######################################################################## 100.0%
######################################################################## 100.0%
==> Downloading https://github.com/developmentseed/landsat-util/archive/v0.2.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/landsat-util-0.2.0.tar.gz
==> Patching
==> python setup.py install --prefix=/usr/local/Cellar/landsat-util/0.2.0/libexec --install-scri
simplejson.tests.__init__: module references __file__
Adding simplejson 3.6.5 to easy-install.pth file

Installed /usr/local/Cellar/landsat-util/0.2.0/libexec/lib/python2.7/site-packages/simplejson-3.6.5-py2.7-macosx-10.10-intel.egg
error: Installed distribution six 1.4.1 conflicts with requirement six>=1.6.1
couldn't understand kern.osversion `14.0.0'

READ THIS: http://git.io/brew-troubleshooting
```
i also ran: 

```
$: pip show six
---
Name: six
Version: 1.9.0
Location: /usr/local/lib/python2.7/site-packages
Requires: 
```
Any suggestions?

**Comment by scisco** [comment] 2015-01-23 22:53
@briantjacobs I couldn't reproduce this error. Could you try running: `pip uninstall six` and then reinstall landsat-util?

**Comment by briantjacobs** [comment] 2015-01-24 02:33
I tried this and ran into the same error as above. Do you know how I can see at what path the installer is finding the outdated `six`?

**Comment by scisco** [comment] 2015-03-10 19:00
@briantjacobs This dependency issues should be resolved in the new version of landsat-util. Closing.

**Closed by scisco** 2015-03-10 19:00 UTC

**Comment by briantjacobs** [comment] 2015-03-12 12:28
Thanks. This worked great.
