### ISSUE TITLE
processing fails on scenes that span 180/-180 (e.g. LC80730712015155LGN00)

### ISSUE THREAD

**Issue by dpl10** [developmentseed/landsat-util#150] opened 2016-02-05 18:30 UTC

**Comment by scisco** [comment] 2016-03-25 18:31
Couldn't reproduce the problem. I was able to successfully process this scene using this: `landsat download LC80730712015155LGN00 -b 432 -p`

**Comment by dpl10** [comment] 2016-03-25 18:43
Did you look at that output file? The program doesnt give an error, but the processed file is just black. I have attached a (compressed) version of what I get.

Damon

 
> On 2016 Mar 25, at 2:31 PM, Scisco <notifications@github.com> wrote:
> 
> Couldn't reproduce the problem. I was able to successfully process this scene using this: landsat download LC80730712015155LGN00 -b 432 -p
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

--------------------------
Damon Little
Associate Curator of Bioinformatics
Cullman Program for Molecular Systematics
The New York Botanical Garden
Bronx, New York 10458-5126
U.S.A.
Tel: 718.817.8521

**Comment by scisco** [comment] 2016-03-25 18:44
@dpl10 ah, you are correct. Will investigate

**Comment by njwilson23** [comment] 2016-04-10 22:41
I took a quick look at this.

`image.BaseProcess._get_boundaries` appears to return incorrect results when crossing the dateline.

If `rasterio.warp.calculate_default_transform` is used rather than the `_get_boundaries` method, the output ends up being identical to calling
```
gdalwarp -t_srs 'EPSG:3857' downloaded.tif processed.tif
````
on the command line. Unfortunately, the ouput spans the globe and the default resolution is strange. I'm not sure if there's a GDAL option somewhere to make it handle the antemeridian better, or if the raster will need to be explicitly split into two, projected to web mercator, and restitched.

**Comment by njwilson23** [comment] 2016-04-14 21:41
Some more thoughts:

It's not really clear to me what "process" is supposed to mean. Sometimes it means compute NDVI, sometimes it means perform pansharpening. If I understand correctly, it reprojects to WebMercator in every case, but this may simply be inappropriate for dateline-spanning edges.

Why does "process" perform any reprojection by default? Would it be better if reprojecting required an additional flag (and maybe even the desired output spatial reference could be a parameter)?

**Comment by matthewhanson** [comment] 2018-07-30 20:43
@dpl10 This continues to be an issue, but we won't be fixing this in landsat-util as we it will deprecated in favor of using our new [sat-api](https://medium.com/devseed/sat-api-an-api-for-spatiotemporal-asset-catalogs-88c3c78fdb0e) and [sat-search](https://github.com/sat-utils/sat-search/).  The processing functionality of landsat-util will be replaced with a new version of [sat-process](https://github.com/sat-utils/sat-process) and we will have to handle that issue there.

**Closed by matthewhanson** 2018-07-30 20:43 UTC
Labels: bug
